# Generated by Django 2.2 on 2020-12-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('tel_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('type', models.CharField(blank=True, max_length=1, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('crt_time', models.DateTimeField(blank=True, null=True)),
                ('crt_user', models.CharField(blank=True, max_length=255, null=True)),
                ('crt_name', models.CharField(blank=True, max_length=255, null=True)),
                ('crt_host', models.CharField(blank=True, max_length=255, null=True)),
                ('upd_time', models.DateTimeField(blank=True, null=True)),
                ('upd_user', models.CharField(blank=True, max_length=255, null=True)),
                ('upd_name', models.CharField(blank=True, max_length=255, null=True)),
                ('upd_host', models.CharField(blank=True, max_length=255, null=True)),
                ('attr1', models.CharField(blank=True, max_length=255, null=True)),
                ('attr2', models.CharField(blank=True, max_length=255, null=True)),
                ('attr3', models.CharField(blank=True, max_length=255, null=True)),
                ('attr4', models.CharField(blank=True, max_length=255, null=True)),
                ('attr5', models.CharField(blank=True, max_length=255, null=True)),
                ('attr6', models.CharField(blank=True, max_length=255, null=True)),
                ('attr7', models.CharField(blank=True, max_length=255, null=True)),
                ('attr8', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
