# Generated by Django 2.2 on 2020-12-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('pubid', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='出版社ID')),
                ('pubname', models.CharField(max_length=50, verbose_name='出版社名称')),
                ('pubaddr', models.CharField(max_length=60, verbose_name='出版社地址')),
                ('pubpost', models.CharField(max_length=10, verbose_name='出版社邮编')),
                ('website', models.CharField(max_length=50, verbose_name='出版社网址')),
                ('contact', models.CharField(max_length=8, verbose_name='联系人')),
                ('contele', models.CharField(max_length=30, verbose_name='联系方式')),
                ('e_mail', models.CharField(max_length=50, verbose_name='联系人E-mail')),
                ('pubinfo', models.TextField(blank=True, verbose_name='备注信息')),
            ],
        ),
    ]
