# Generated by Django 2.2 on 2020-12-17 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='书籍编号')),
                ('bookname', models.CharField(max_length=50, verbose_name='书籍名称')),
                ('authorname', models.CharField(max_length=50, verbose_name='作者名称')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Publisher', verbose_name='出版社')),
            ],
        ),
    ]
