# Generated by Django 2.2 on 2020-12-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authorname',
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorid', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='作者编号')),
                ('authorname', models.CharField(max_length=50, verbose_name='作者名称')),
                ('book', models.ManyToManyField(to='books.Book', verbose_name='出版书籍')),
            ],
        ),
    ]
