# Generated by Django 2.2 on 2020-12-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rank',
            field=models.IntegerField(default=1, verbose_name='级别'),
        ),
    ]
